add awayUntil for members
open-dme/open-dme-server pull request #29
Opened 2024-07-18 17:59 UTC by Integer93

closes #23

- Added awayUntil as Date field in member
  - used date because it is easy to use, easy to serialize and we don´t want to deal with timezones
- Added controller mapping to set it

2024-07-18 18:01 UTC, rainbowdashlabs commented
Simply use timestamps in UTC. Thats the easy way. Not being able to mark yourself away for a few hours is kinda useless, because thats the most common use case.

2024-07-19 15:13 UTC, yannicklamprecht requested changes

2024-07-19 15:13 UTC, yannicklamprecht commented on src/main/java/io/github/opendme/server/controller/MemberController.java
> +    public void setStatus(@PathVariable Long memberId, @RequestBody Date awayUntil) {
Use OffsetDateTime instead to address @rainbowdashlabs remarks and to directly use modern date time types.

2024-07-19 15:13 UTC, yannicklamprecht commented on src/main/java/io/github/opendme/server/entity/Member.java
> +    private Date awayUntil;
private OffsetDateTime awayUntil;

2024-07-19 17:15 UTC, Integer93 commented
Date also contains the time. A date is basically 01.01.24 19:00:00. So its precise enough.
And its easy to serialize, every other DateTime variant was annoying.

I will try the Offset variant.

2024-07-19 18:40 UTC, yannicklamprecht approved these changes

2024-07-19 18:57 UTC, merged

2024-07-19 19:04 UTC, Integer93 commented
awayUntil ist now patchable with miliseconds since unix epoch.
See https://currentmillis.com/