call response creation without call + call creation
open-dme/open-dme-server pull request #43
Opened 2024-07-22 10:05 UTC by Integer93

Closes #41 
Closes #42 

Member can now create a CallResponse without a call.
If there are >= 3 responses within 5 min, a call will be created and attached to them.

2024-07-22 12:37 UTC, yannicklamprecht requested changes

2024-07-22 12:37 UTC, yannicklamprecht commented on src/main/java/io/github/opendme/server/service/CallService.java
> +    public static final int AUTO_DISPATCH_THRESHOLD = 3;
Make both values configurable.

2024-07-22 12:37 UTC, yannicklamprecht commented on src/main/java/io/github/opendme/server/entity/CallResponseRepository.java
> +    List<CallResponse> findAllByMember_Department_IdAndCreatedAtAfterAndCallNull(Long id, LocalDateTime createdAt);
I assume the underscore is needed?

2024-07-22 12:37 UTC, yannicklamprecht commented on src/test/java/io/github/opendme/server/controller/CallControllerIT.java
> +
Just auto wire the object mapper. There is a bean declared in TestGlobalBeans or how the class is called.

2024-07-23 19:38 UTC, Integer93 commented on src/main/java/io/github/opendme/server/entity/CallResponseRepository.java
> +    List<CallResponse> findAllByMember_Department_IdAndCreatedAtAfterAndCallNull(Long id, LocalDateTime createdAt);
Ah i didn't check that.
It also works without them.

2024-07-23 19:46 UTC, Integer93 commented on src/main/java/io/github/opendme/server/service/CallService.java
> +    public static final int AUTO_DISPATCH_THRESHOLD = 3;
I just used `@Value` in the service and put them in the profile. Hope that's enough.

2024-07-23 21:15 UTC, yannicklamprecht approved these changes

2024-07-23 21:15 UTC, merged